# Generated by Django 2.2.7 on 2022-04-27 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20220426_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='parament_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_tag', to='quiz.Tag'),
        ),
    ]
